#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: {{ .Release.Name }}-tftp
#  namespace: {{ .Release.Namespace }}
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#  storageClassName: standard-rwo
