---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredhcp
  namespace: {{ .Release.Namespace }}
  labels:
    app: coredhcp
spec:
  replicas: {{ .Values.coredhcp.deployment.replicaCount }}
  selector:
    matchLabels:
      app: coredhcp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: coredhcp
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/coredhcp/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: coredhcp
          image: {{ .Values.coredhcp.deployment.image.repository }}/{{ .Values.coredhcp.deployment.image.name }}:{{ .Values.coredhcp.deployment.image.tag }}
          imagePullPolicy: {{ .Values.coredhcp.deployment.image.pullPolicy }}
          args:
            - "/coredhcp"
            - "-L"
            - "debug"
          ports:
            - name: dhcp
              # TODO we're an IRC server now! probably just have the LB dispatch to a high port
              # I don't think this will actually need net admin/the real DHCP port if we're forwarding
              containerPort: 6667
              protocol: UDP
          volumeMounts:
            - mountPath: /leases
              name: leases
            - mountPath: /etc/coredhcp/
              name: config
      volumes:
        - name: leases
          emptyDir:
            sizeLimit: 512M
        - name: config
          configMap:
            name: coredhcp
